name: electrondensity

channels:
    - rdkit
    - conda-forge
dependencies:
    - python
    - ipython
    - tqdm
    - rdkit==2020.03.2.0
    - matplotlib
    - tensorflow-gpu=2.3.2
    - xtb
    - requests
    - Cython
    - numpy
    - scipy
    - matplotlib
    - h5py
    - argh
