name: ed_tf12

channels:
    - rdkit
    - conda-forge
dependencies:
    - cudatoolkit=11.8.0
    - python=3.9
    - ipython
    - tqdm
    - rdkit
    - xtb=6.4.1
    - requests
    - argh
    - matplotlib
    - scipy
    - cython
    - traits=6.1.1
    - traitsui=7.0.0
    - mayavi
    - pip
    - pip:
      - nvidia-cudnn-cu11==8.6.0.163
      - tensorflow==2.12.*

