name: electrondensity

channels:
    - rdkit
    - conda-forge
dependencies:
    - python=3.9
    - ipython
    - tqdm
    - rdkit
    - xtb
    - requests
    - argh
    - matplotlib
    - scipy
    - cython
    - traits=6.1.1
    - traitsui=7.0.0
    - mayavi
    - pip
    - pip:
      - tensorflow==2.5.0

