name: electrondensity

channels:
    - rdkit
    - conda-forge
dependencies:
    - python=3.9
    - ipython
    - tqdm
    - rdkit
    - xtb
    - requests
    - argh
    - matplotlib
    - scipy
    - cython
    - pip
    - pip:
      - tensorflow

